export const PERMISSIONS = {
  CREATE_BRANCH: 'CREATE_BRANCH',
  READ_BRANCH: 'READ_BRANCH',
  UPDATE_BRANCH_STATUS: 'UPDATE_BRANCH_STATUS',
  UPDATE_BRANCH: 'UPDATE_BRANCH',
  
  CREATE_USER: 'CREATE_USER',
  READ_USER: 'READ_USER',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_STATUS: 'UPDATE_USER_STATUS',
  APPROVE_USER: 'APPROVE_USER',
  REJECT_USER: 'REJECT_USER',
  
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  READ_CATEGORY: 'READ_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  ARCHIVE_CATEGORY: 'ARCHIVE_CATEGORY',
  RESTORE_CATEGORY: 'RESTORE_CATEGORY',
  
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  READ_PRODUCT: 'READ_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  ARCHIVE_PRODUCT: 'ARCHIVE_PRODUCT',
  RESTORE_PRODUCT: 'RESTORE_PRODUCT',
  
  CREATE_INVENTORY: 'CREATE_INVENTORY',
  READ_INVENTORY: 'READ_INVENTORY',
  UPDATE_INVENTORY: 'UPDATE_INVENTORY',
  RESTOCK_INVENTORY: 'RESTOCK_INVENTORY',
  ADJUST_INVENTORY: 'ADJUST_INVENTORY',
  TRANSFER_INVENTORY: 'TRANSFER_INVENTORY',
  READ_INVENTORY_HISTORY: 'READ_INVENTORY_HISTORY',
  
  CREATE_SUPPLIER: 'CREATE_SUPPLIER',
  READ_SUPPLIER: 'READ_SUPPLIER',
  UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
  ARCHIVE_SUPPLIER: 'ARCHIVE_SUPPLIER',
  RESTORE_SUPPLIER: 'RESTORE_SUPPLIER',

  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  READ_CUSTOMER: 'READ_CUSTOMER',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  ARCHIVE_CUSTOMER: 'ARCHIVE_CUSTOMER',
  RESTORE_CUSTOMER: 'RESTORE_CUSTOMER',

  CREATE_ORDER: 'CREATE_ORDER',
  READ_ORDER: 'READ_ORDER',

  READ_REPORTS: 'READ_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',

  CREATE_BILL: 'CREATE_BILL',
  VOID_BILL: 'VOID_BILL',
  REFUND_BILL: 'REFUND_BILL',

  CREATE_INGREDIENT: 'CREATE_INGREDIENT',
  READ_INGREDIENT: 'READ_INGREDIENT',
  UPDATE_INGREDIENT: 'UPDATE_INGREDIENT',
  ARCHIVE_INGREDIENT: 'ARCHIVE_INGREDIENT',
  RESTORE_INGREDIENT: 'RESTORE_INGREDIENT',
  RESTOCK_INGREDIENT: 'RESTOCK_INGREDIENT',
  ADJUST_INGREDIENT: 'ADJUST_INGREDIENT',
  TRANSFER_INGREDIENT: 'TRANSFER_INGREDIENT',
  READ_INGREDIENT_HISTORY: 'READ_INGREDIENT_HISTORY',
  READ_AUDIT: 'READ_AUDIT'
};
